/**
 * Cross-run learned knowledge injection.
 *
 * Reads ~/.pi/agent/super-dev/learned-index.json (generated by the reflection
 * agent), filters by agent name, sorts by score, and returns a formatted string
 * for injection into the agent's system prompt.
 *
 * Tier 1: top-N full entries (pre-loaded, always visible).
 * Tier 2: next-M index entries (titles + scores, agent can grep the full file).
 * + File path for on-demand depth search.
 *
 * Cold start: if learned-index.json doesn't exist yet, returns "" (no injection).
 */

import { readFileSync, existsSync } from "node:fs";
import { getLearnedIndexPath, getLearnedPath, getConfig } from "./super-dev-dir.ts";

interface LearnedIndex {
	totalEntries: number;
	entries: Record<string, {
		title: string;
		score: number;
		tags: { agent: string; stage: string; lang: string };
		line?: number;
		summary: string;
	}>;
	byAgent: Record<string, string[]>;
	byLang: Record<string, string[]>;
	topOverall: string[];
}

/** Load and format learned lessons for an agent's system prompt. Returns "" if
 *  no learned-index.json exists (cold start). */
export function loadLearnedLessons(agentName: string): string {
	const indexPath = getLearnedIndexPath();
	if (!existsSync(indexPath)) return "";

	let index: LearnedIndex;
	try { index = JSON.parse(readFileSync(indexPath, "utf8")); } catch { return ""; }

	const config = getConfig();
	const topN = config.topNPreload;
	const listSize = config.indexListSize;

	// Filter: entries for this agent + any-language entries
	const byAgent = index.byAgent[agentName] ?? [];
	const byAny = index.byLang["any"] ?? [];
	const relevantIds = [...new Set([...byAgent, ...byAny])];
	if (relevantIds.length === 0) return "";

	// Map to entries, sort by score descending
	const relevant = relevantIds
		.map((id) => index.entries[id])
		.filter(Boolean)
		.sort((a, b) => b.score - a.score);
	if (relevant.length === 0) return "";

	// Tier 1: top-N full entries
	const topNEntries = relevant.slice(0, topN);
	// Tier 2: next-M index entries (title + score only)
	const indexEntries = relevant.slice(topN, topN + listSize);

	const lines: string[] = [
		"## Lessons from past runs (top-scored, pre-loaded)",
		...topNEntries.map((e) => `### [score:${e.score}] ${e.title}\n${e.summary}`),
		"",
		"## More lessons (grep for details)",
		`File: ${getLearnedPath()}`,
		...indexEntries.map((e) => `- [score:${e.score}] ${e.title}`),
	];
	if (relevant.length > topN + listSize) {
		lines.push(`... and ${relevant.length - topN - listSize} more`);
	}
	return lines.join("\n");
}
