/**
 * Cross-run learned knowledge injection.
 *
 * Reads ~/.super-dev/learned-index.json (generated by the reflection
 * agent), filters by agent name, sorts by score, and returns a formatted string
 * for injection into the agent's system prompt.
 *
 * Tier 1: top-N full entries (pre-loaded, always visible).
 * Tier 2: next-M index entries (titles + scores, agent can grep the full file).
 * + File path for on-demand depth search.
 *
 * Cold start: if learned-index.json doesn't exist yet, returns "" (no injection).
 *
 * P3 / §8.1 contamination firewall (the MECHANICAL half of the reflection
 * exclusion — prompts are advisory, P4): before any entry is injected, the
 * parsed index is scanned against the raw golden-case texts (literal canary
 * GUID + 7-gram overlap; evolution/contamination.ts — a pure leaf import,
 * no eval-layer cycle). A flagged entry is QUARANTINED: dropped here, never
 * injected, warned loudly, and durably recorded by the flywheel-run scan in
 * ~/.super-dev/evals/contamination.jsonl. The seam re-scans per load on
 * purpose — enforcement must not depend on the ledger having been written
 * first (detection is cheap, personal-tool scale). The whole firewall layer
 * is fail-open: it can never break prompt assembly (P4/P5).
 */

import { readFileSync, existsSync } from "node:fs";
import { getLearnedIndexPath, getLearnedPath, getConfig } from "./super-dev-dir.ts";
import { loadGoldenCaseTexts, scanLearnedIndexEntries } from "../evolution/contamination.ts";

interface LearnedIndex {
	totalEntries: number;
	entries: Record<string, {
		title: string;
		score: number;
		tags: { agent: string; stage: string; lang: string };
		line?: number;
		summary: string;
	}>;
	byAgent: Record<string, string[]>;
	byLang: Record<string, string[]>;
	topOverall: string[];
}

/**
 * §8.1: the entry ids this load must NOT inject (golden-case contamination —
 * canary hit or 7-gram overlap). Pure given (index, caseTexts); never throws;
 * LOUD per entry (a silent quarantine would hide an instrument fault).
 */
function contaminatedEntryIds(index: LearnedIndex, caseTexts: ReturnType<typeof loadGoldenCaseTexts>): Set<string> {
	const blocked = new Set<string>();
	if (caseTexts.length === 0) return blocked; // nothing to protect — cold start
	for (const f of scanLearnedIndexEntries(index, caseTexts)) {
		if (!blocked.has(f.entryId)) {
			blocked.add(f.entryId);
			console.warn(`[super-dev] contamination firewall: quarantined learned-index entry "${f.entryId}" (${f.trigger}, golden case ${f.caseId}) — never injected; see ~/.super-dev/evals/contamination.jsonl (§8.1)`);
		}
	}
	return blocked;
}

/** Load and format learned lessons for an agent's system prompt. Returns "" if
 *  no learned-index.json exists (cold start). */
export function loadLearnedLessons(agentName: string): string {
	const indexPath = getLearnedIndexPath();
	if (!existsSync(indexPath)) return "";

	let index: LearnedIndex;
	try { index = JSON.parse(readFileSync(indexPath, "utf8")); } catch { return ""; }

	const config = getConfig();
	const topN = config.topNPreload;
	const listSize = config.indexListSize;

	// Filter: entries for this agent + any-language entries
	const byAgent = index.byAgent[agentName] ?? [];
	const byAny = index.byLang["any"] ?? [];
	const relevantIds = [...new Set([...byAgent, ...byAny])];
	if (relevantIds.length === 0) return "";

	// §8.1 firewall: quarantine contaminated entries BEFORE any injection.
	let blocked = new Set<string>();
	try {
		blocked = contaminatedEntryIds(index, loadGoldenCaseTexts());
	} catch { /* fail-open: the firewall must never break prompt assembly */ }

	// Map to entries (id-tagged for the quarantine filter), sort by score descending
	const relevant = relevantIds
		.map((id) => ({ id, entry: index.entries[id] }))
		.filter((r): r is { id: string; entry: LearnedIndex["entries"][string] } => Boolean(r.entry) && !blocked.has(r.id))
		.sort((a, b) => b.entry.score - a.entry.score);
	if (relevant.length === 0) return "";

	// Tier 1: top-N full entries
	const topNEntries = relevant.slice(0, topN);
	// Tier 2: next-M index entries (title + score only)
	const indexEntries = relevant.slice(topN, topN + listSize);

	const lines: string[] = [
		"## Lessons from past runs (top-scored, pre-loaded)",
		...topNEntries.map((e) => `### [score:${e.entry.score}] ${e.entry.title}\n${e.entry.summary}`),
		"",
		"## More lessons (grep for details)",
		`File: ${getLearnedPath()}`,
		...indexEntries.map((e) => `- [score:${e.entry.score}] ${e.entry.title}`),
	];
	if (relevant.length > topN + listSize) {
		lines.push(`... and ${relevant.length - topN + listSize} more`);
	}
	return lines.join("\n");
}
