/**
 * v0.3.69 E2 — POST-MORTEM: read-only incident diagnosis → inbox draft.
 *
 * Plan §9.3 E2 (Weng "Harness Engineering", Agent Debugger): experience
 * observability was manual; this automates the DRAFT half. A read-only
 * sd-post-mortem agent (agents/post-mortem.md) reads the run's artifacts —
 * PATHS in the prompt, JIT reading, the agent never receives full logs —
 * matches the failure to the P1–P10 escape classes, and returns a STRUCTURED
 * draft via <control>. The ENGINE validates and writes the draft to
 * docs/findings/inbox/ (P4: the agent itself can never write — prompts are
 * advisory; the boundary is mechanical). The Decide gate stays human (E3).
 * Auto-invocation requires config `postMortem: "auto"` (default manual) and
 * a non-success status — safety-first per plan §9.3.
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { runAgentViaDelegation } from "../agents/delegation-backend.ts";
import { extractControl } from "../control.ts";
import type { RunMetricsRow } from "./sigma-bands.ts";

export type PostMortemMode = "auto" | "manual";

export interface FindingEvidence {
	source: string;
	quote: string;
}

export interface FindingDraft {
	title: string;
	escapeClass: string;
	evidence: FindingEvidence[];
	rootCauseHypothesis: string;
	proposedFix: string;
	pinningTest: string;
	prediction?: { metric: string; direction: "increase" | "decrease" };
	confidence?: string;
}

/** Gate: only non-success runs, and only when the operator opted into auto. */
export function shouldAutoPostMortem(status: string, mode: PostMortemMode | undefined): boolean {
	return status !== "success" && mode === "auto";
}

const PREDICTION_METRICS = new Set(["wallMs", "costUsd", "tokens", "agentErrorRounds", "fatalAborts", "agentsSpawned"]);

/** Fail-closed validation (the engine refuses to write junk drafts). */
export function validateFindingDraft(d: unknown): d is FindingDraft {
	if (!d || typeof d !== "object") return false;
	const draft = d as Partial<FindingDraft>;
	if (typeof draft.title !== "string" || draft.title.trim().length < 8) return false;
	if (!Array.isArray(draft.evidence) || draft.evidence.length === 0) return false;
	for (const e of draft.evidence) {
		if (!e || typeof e !== "object" || typeof (e as FindingEvidence).source !== "string" || typeof (e as FindingEvidence).quote !== "string") return false;
	}
	if (typeof draft.rootCauseHypothesis !== "string" || draft.rootCauseHypothesis.trim().length === 0) return false;
	const p = draft.prediction;
	if (!p || typeof p !== "object") return false;
	if (typeof p.metric !== "string" || !PREDICTION_METRICS.has(p.metric)) return false;
	if (p.direction !== "increase" && p.direction !== "decrease") return false;
	return true;
}

/** Deterministic markdown draft (governance header first — advisory-only). */
export function renderFindingDraft(d: FindingDraft, ctx: { runId: string; status: string }): string {
	const evidence = d.evidence.map((e) => `- \`${e.source}\`: > ${e.quote}`).join("\n");
	return `# Finding draft: ${d.title}

> status: draft — advisory-only, awaiting human triage (E3). Generated by the
> read-only post-mortem agent; nothing in this file has been applied.
> run: ${ctx.runId} (status: ${ctx.status}) · escape class: ${d.escapeClass} · confidence: ${d.confidence ?? "unspecified"}

## Evidence (quoted from artifacts)

${evidence}

## Root-cause hypothesis

${d.rootCauseHypothesis}

## Proposed class-level fix

${d.proposedFix}

## Pinning test

${d.pinningTest}

## Prediction (falsifiable — E1 verifies against later runs)

prediction: ${d.prediction!.metric} ${d.prediction!.direction}
`;
}

function slugify(s: string): string {
	return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60) || "finding";
}

/** Timestamped inbox write; same-second collisions get a counter (never overwrite). */
export function writeFindingDraft(inboxDir: string, d: FindingDraft, ctx: { runId: string; status: string }): string {
	mkdirSync(inboxDir, { recursive: true });
	const base = `${new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19)}-${slugify(d.title)}`;
	let path = join(inboxDir, `${base}.md`);
	let n = 2;
	while (existsSync(path)) {
		path = join(inboxDir, `${base}-${n++}.md`);
	}
	writeFileSync(path, renderFindingDraft(d, ctx), "utf8");
	return path;
}

/** The extension repo's docs/findings/inbox/ (drafts belong to the HARNESS
 *  repo, not the target worktree). Derived from this module's own location. */
export function defaultInboxDir(): string {
	const here = fileURLToPath(new URL(".", import.meta.url)); // …/src/evolution/
	return join(here, "..", "..", "docs", "findings", "inbox");
}

export interface PostMortemInput {
	events: unknown;
	inboxDir?: string;
	runId: string;
	status: string;
	metricsRow: RunMetricsRow;
	artifactPaths: { runLog?: string; eventsJsonl?: string; specDir?: string };
	log?: (m: string) => void;
}

export interface PostMortemOutput {
	draftPath?: string;
	error?: string;
}

/** Delegate sd-post-mortem; engine validates + writes the inbox draft. */
export async function runPostMortem(input: PostMortemInput): Promise<PostMortemOutput> {
	const inbox = input.inboxDir ?? defaultInboxDir();
	const paths = [
		input.artifactPaths.runLog ? `- run log: ${input.artifactPaths.runLog}` : "",
		input.artifactPaths.eventsJsonl ? `- events ledger: ${input.artifactPaths.eventsJsonl}` : "",
		input.artifactPaths.specDir ? `- spec dir: ${input.artifactPaths.specDir}` : "",
	].filter(Boolean).join("\n");
	const task = `Post-mortem run ${input.runId} (status: ${input.status}).

## Run-metrics row (the frame)

\`\`\`json
${JSON.stringify(input.metricsRow)}
\`\`\`

## Artifact paths (read just-in-time, grep the failure signatures first)

${paths}

Follow agents/post-mortem.md exactly: quote evidence with file:line, match the
P1–P10 escape class (or "unknown"), propose the class-level fix + pinning test,
and end with the <control> JSON draft. You are read-only; the engine writes
the draft file.`;
	const result = await runAgentViaDelegation({
		agent: "post-mortem",
		prompt: task,
		cwd: input.artifactPaths.specDir ?? process.cwd(),
		timeoutMs: 240_000,
		controlKeys: ["title", "escapeClass", "evidence", "rootCauseHypothesis", "proposedFix", "pinningTest", "prediction", "confidence"],
		events: input.events as never,
		ownerRunId: `post-mortem-${input.runId}`.slice(0, 256).replace(/[\n\r]/g, ""),
		id: "pipeline.post-mortem",
	});
	if (result.error) return { error: result.error };
	const draft = result.control as unknown;
	if (!validateFindingDraft(draft)) {
		return { error: `post-mortem returned no valid finding draft (control ${draft ? "failed validation" : "absent"}) — nothing written` };
	}
	const draftPath = writeFindingDraft(inbox, draft, { runId: input.runId, status: input.status });
	input.log?.(`post-mortem: finding draft written to ${draftPath} (advisory-only — triage with E3)`);
	return { draftPath };
}
